quadrantChart
    title Analytics and Business Intelligence Platforms
    x-axis Completeness of Vision --> x-axis-2
    y-axis Ability to Execute --> y-axis-2
    quadrant-1 Leaders
    quadrant-2 Challengers
    quadrant-3 Niche Players
    quadrant-4 Visionaries
    Microsoft: [0.75, 0.75] radius: 10
    Salesforce: [0.55, 0.60] radius: 8
    SAP: [0.70, 0.65]
    IBM: [0.51, 0.40]
    Oracle: [0.65, 0.55]
    Qlik: [0.60, 0.45]
    Tableau: [0.68, 0.72]
    SAS: [0.45, 0.58]
    MicroStrategy: [0.50, 0.50]
    Alteryx: [0.35, 0.42]
    Sisense: [0.30, 0.35]
    ThoughtSpot: [0.25, 0.45]
    Domo: [0.20, 0.30]
    Looker: [0.55, 0.52]
    Amazon: [0.80, 0.68] color: #ff9900
    Google: [0.72, 0.60] color: #4285f4
